projects:
  xyz89:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: aa54ednnsrgerokl7izxsxuxii
      endpoints:
        prod: >-
          https://wu46hvqs6zg7hjwz74q47gyvke.appsync-api.us-east-1.amazonaws.com/graphql
